--
-- PostgreSQL database dump
--

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: labo_article; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_article (
    id bigint NOT NULL,
    titre character varying(200) NOT NULL,
    contenu text NOT NULL,
    image_principale character varying(100),
    date_creation timestamp with time zone NOT NULL,
    date_modification timestamp with time zone NOT NULL,
    est_publie boolean NOT NULL,
    auteur_id bigint NOT NULL,
    commentaire_validation text,
    date_validation timestamp with time zone,
    statut_validation character varying(20) NOT NULL,
    validateur_id integer
);


ALTER TABLE public.labo_article OWNER TO postgres;

--
-- Name: labo_article_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_article_categories (
    id bigint NOT NULL,
    article_id bigint NOT NULL,
    categorie_id bigint NOT NULL
);


ALTER TABLE public.labo_article_categories OWNER TO postgres;

--
-- Name: labo_article_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_article_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_article_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_article_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_categorie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_categorie (
    id bigint NOT NULL,
    nom character varying(100) NOT NULL,
    description text
);


ALTER TABLE public.labo_categorie OWNER TO postgres;

--
-- Name: labo_categorie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_categorie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_categorie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_collaborateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_collaborateur (
    id bigint NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    titre character varying(100) NOT NULL,
    institution character varying(200) NOT NULL,
    description text NOT NULL,
    photo character varying(100),
    email character varying(254),
    lien character varying(200)
);


ALTER TABLE public.labo_collaborateur OWNER TO postgres;

--
-- Name: labo_collaborateur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_collaborateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_collaborateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_devenir; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_devenir (
    id bigint NOT NULL,
    entreprise character varying(200) NOT NULL,
    poste character varying(200) NOT NULL,
    description text NOT NULL,
    realisations text,
    date_debut date NOT NULL,
    lieu character varying(200) NOT NULL,
    lien character varying(200),
    domaine character varying(100) NOT NULL,
    type_structure character varying(20) NOT NULL,
    membre_id bigint NOT NULL
);


ALTER TABLE public.labo_devenir OWNER TO postgres;

--
-- Name: labo_devenir_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_devenir ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_devenir_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_evenement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_evenement (
    id bigint NOT NULL,
    titre character varying(200) NOT NULL,
    description text NOT NULL,
    type_evenement character varying(20) NOT NULL,
    date_debut timestamp with time zone NOT NULL,
    date_fin timestamp with time zone NOT NULL,
    lieu character varying(200) NOT NULL,
    image character varying(100)
);


ALTER TABLE public.labo_evenement OWNER TO postgres;

--
-- Name: labo_evenement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_evenement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_evenement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_historiquetheme; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_historiquetheme (
    id bigint NOT NULL,
    date_debut date NOT NULL,
    date_fin date,
    description text NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    membre_id bigint NOT NULL,
    theme_id bigint NOT NULL
);


ALTER TABLE public.labo_historiquetheme OWNER TO postgres;

--
-- Name: labo_historiquetheme_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_historiquetheme ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_historiquetheme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_imagepresentation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_imagepresentation (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    legende character varying(200),
    presentation_id bigint NOT NULL
);


ALTER TABLE public.labo_imagepresentation OWNER TO postgres;

--
-- Name: labo_imagepresentation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_imagepresentation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_imagepresentation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_invitation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_invitation (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    token character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL,
    inviter_id integer NOT NULL
);


ALTER TABLE public.labo_invitation OWNER TO postgres;

--
-- Name: labo_invitation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_invitation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_invitation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_membre; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_membre (
    id bigint NOT NULL,
    photo character varying(100),
    titre character varying(100) NOT NULL,
    bio text NOT NULL,
    linkedin character varying(200),
    github character varying(200),
    theme_id bigint,
    user_id integer NOT NULL,
    date_arrivee date NOT NULL,
    date_depart date,
    est_ancien boolean NOT NULL,
    est_responsable boolean NOT NULL,
    portfolio character varying(200),
    statut_ancien character varying(20),
    profil_valide boolean DEFAULT false,
    date_validation_profil timestamp without time zone,
    validateur_profil_id integer
);


ALTER TABLE public.labo_membre OWNER TO postgres;

--
-- Name: labo_membre_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_membre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_membre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_membre_themes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_membre_themes (
    id integer NOT NULL,
    membre_id integer NOT NULL,
    theme_id integer NOT NULL
);


ALTER TABLE public.labo_membre_themes OWNER TO postgres;

--
-- Name: labo_membre_themes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.labo_membre_themes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.labo_membre_themes_id_seq OWNER TO postgres;

--
-- Name: labo_membre_themes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.labo_membre_themes_id_seq OWNED BY public.labo_membre_themes.id;


--
-- Name: labo_presentation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_presentation (
    id bigint NOT NULL,
    titre character varying(200) NOT NULL,
    description text NOT NULL,
    fichier character varying(100) NOT NULL,
    type_fichier character varying(10) NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    date_modification timestamp with time zone NOT NULL,
    membre_id bigint NOT NULL,
    theme_id bigint,
    fichier_public boolean DEFAULT false
);


ALTER TABLE public.labo_presentation OWNER TO postgres;

--
-- Name: labo_presentation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_presentation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_presentation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_projet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_projet (
    id bigint NOT NULL,
    titre character varying(200) NOT NULL,
    description text NOT NULL,
    date_debut date NOT NULL,
    statut character varying(20) NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    est_public boolean NOT NULL,
    responsable_id bigint NOT NULL,
    theme_id bigint
);


ALTER TABLE public.labo_projet OWNER TO postgres;

--
-- Name: labo_projet_collaborateurs_externes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_projet_collaborateurs_externes (
    id bigint NOT NULL,
    projet_id bigint NOT NULL,
    collaborateur_id bigint NOT NULL
);


ALTER TABLE public.labo_projet_collaborateurs_externes OWNER TO postgres;

--
-- Name: labo_projet_collaborateurs_externes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_projet_collaborateurs_externes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_projet_collaborateurs_externes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_projet_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_projet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_projet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_projet_participants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_projet_participants (
    id bigint NOT NULL,
    projet_id bigint NOT NULL,
    membre_id bigint NOT NULL
);


ALTER TABLE public.labo_projet_participants OWNER TO postgres;

--
-- Name: labo_projet_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_projet_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_projet_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_temoignage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_temoignage (
    id bigint NOT NULL,
    nom character varying(100) NOT NULL,
    role character varying(100) NOT NULL,
    contenu text NOT NULL,
    photo character varying(100),
    date date NOT NULL
);


ALTER TABLE public.labo_temoignage OWNER TO postgres;

--
-- Name: labo_temoignage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_temoignage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_temoignage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_theme; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labo_theme (
    id bigint NOT NULL,
    nom character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.labo_theme OWNER TO postgres;

--
-- Name: labo_theme_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labo_theme ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labo_theme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labo_membre_themes id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_membre_themes ALTER COLUMN id SET DEFAULT nextval('public.labo_membre_themes_id_seq'::regclass);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add categorie	7	add_categorie
26	Can change categorie	7	change_categorie
27	Can delete categorie	7	delete_categorie
28	Can view categorie	7	view_categorie
29	Can add contact	8	add_contact
30	Can change contact	8	change_contact
31	Can delete contact	8	delete_contact
32	Can view contact	8	view_contact
33	Can add evenement	9	add_evenement
34	Can change evenement	9	change_evenement
35	Can delete evenement	9	delete_evenement
36	Can view evenement	9	view_evenement
37	Can add membre	10	add_membre
38	Can change membre	10	change_membre
39	Can delete membre	10	delete_membre
40	Can view membre	10	view_membre
41	Can add temoignage	11	add_temoignage
42	Can change temoignage	11	change_temoignage
43	Can delete temoignage	11	delete_temoignage
44	Can view temoignage	11	view_temoignage
45	Can add theme	12	add_theme
46	Can change theme	12	change_theme
47	Can delete theme	12	delete_theme
48	Can view theme	12	view_theme
49	Can add presentation	13	add_presentation
50	Can change presentation	13	change_presentation
51	Can delete presentation	13	delete_presentation
52	Can view presentation	13	view_presentation
53	Can add image presentation	14	add_imagepresentation
54	Can change image presentation	14	change_imagepresentation
55	Can delete image presentation	14	delete_imagepresentation
56	Can view image presentation	14	view_imagepresentation
57	Can add article	15	add_article
58	Can change article	15	change_article
59	Can delete article	15	delete_article
60	Can view article	15	view_article
61	Can add Collaborateur	16	add_collaborateur
62	Can change Collaborateur	16	change_collaborateur
63	Can delete Collaborateur	16	delete_collaborateur
64	Can view Collaborateur	16	view_collaborateur
65	Can add Devenir	17	add_devenir
66	Can change Devenir	17	change_devenir
67	Can delete Devenir	17	delete_devenir
68	Can view Devenir	17	view_devenir
69	Can add Invitation	18	add_invitation
70	Can change Invitation	18	change_invitation
71	Can delete Invitation	18	delete_invitation
72	Can view Invitation	18	view_invitation
73	Can add Projet	19	add_projet
74	Can change Projet	19	change_projet
75	Can delete Projet	19	delete_projet
76	Can view Projet	19	view_projet
77	Can add Historique de thème	20	add_historiquetheme
78	Can change Historique de thème	20	change_historiquetheme
79	Can delete Historique de thème	20	delete_historiquetheme
80	Can view Historique de thème	20	view_historiquetheme
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
5	pbkdf2_sha256$600000$peEvB4CLS5VJVpi3YTlSdk$c/JGabV3j/UZAgrpuSnvWJ51SBEsG4gbwo6J5m/WH/0=	\N	f	Franck	Franck	Feuwo	valeretamwo@gmail.com	f	t	2025-04-23 15:14:14.31592+00
13	pbkdf2_sha256$600000$eL4fme306y5UQiTarvxDyM$Px42K1t+kDwtsZWIv64JFCxKuvGOEtYY3200+iFWr5Q=	\N	f	Thomas Messi Nguele	Thomas	Messi Nguele	thomas.messi@facsciences-uy1.cm	f	t	2025-05-14 15:19:51.321614+00
15	pbkdf2_sha256$600000$g2LwKZ0yo6oPIoS0isoqor$vhtauom9hQRcTQ2DYnuqSlBbh9zWw6ytgSzAVqNmXxc=	\N	f	BRICE EKANE APAH	BRICE 	EKANE APAH	brice.ekane@univ-rennes.fr	f	t	2025-05-14 15:30:40.553016+00
17	pbkdf2_sha256$600000$l7qtmOHWZc0g6BfciEIQmY$eCf6c/36tBpUlKEZlvmk9iet2jBRWbN9uJ99SUWFeiM=	\N	f	 Mvondo Djob	Djob	 Mvondo	djobiii2078@gmail.com	f	t	2025-05-14 15:52:38.71449+00
14	pbkdf2_sha256$600000$Nbpzg315L60P2NTgTM6WiG$9Xazlgbm5ZJhXf/9Ze82abvX09EH/Z5D7crbyluH9wY=	2025-06-20 16:49:34.322717+00	f	RTTI	RUDY TCHAMBA	TCHAPTCHE ITIEL	tchaptche.rudy@facsciences-uy1.cm	f	t	2025-05-14 15:22:11.352059+00
18	pbkdf2_sha256$600000$dyXWS0svIAUOXq19S7qXcL$g2xiC/4EuV7Og5wwWe1ZZ41/UVOLqMMTxYmj8M/wGus=	2025-06-06 08:46:20.086768+00	f	minsih	Lado	SAHA	ladokihosaha@gmail.com	f	t	2025-05-14 19:50:06.236624+00
19	pbkdf2_sha256$600000$0AN9Iq10o03vF55erYLyw1$1c5OIvsWGnVO8oA/yw/1GBvzXrdge6W6d5eAb68sGJ0=	\N	f	lontsi1	Lambou	Lontsi	lontsilambou@gmail.com	f	t	2025-09-02 16:16:28.484755+00
4	pbkdf2_sha256$600000$O9rA0jIEyLp5JFCmGQJm2J$lFnfW7fXvHJaLrnyijmfKEPwYTnFwlvUczGNyw5BQw8=	2025-04-23 15:09:02.7398+00	f	Fetue Nathanael	Nathanael	Fetue	tetuch@gmail.com	f	t	2025-04-23 12:44:36.090141+00
11	pbkdf2_sha256$600000$PmL5PS3XTfQOiO5s23OEjz$BeXC8F96Ojz/zlDMr/zzWpvRcnY+4lEMCl68CdhfCaI=	2025-05-14 19:33:22.824477+00	f	zaz	Achaire	ZOGO	achaire.zogo@facsciences-uy1.cm	f	t	2025-05-14 15:07:59.399687+00
16	pbkdf2_sha256$600000$t2Wya3yDIl0TN3zzpbpIwN$D+imYjZJh8/6917Jn7j8XxUK6pI24FpH662SOeZ0NAE=	\N	f	Tapamo	Hyppolite	TAPAMO KENFACK	hippolyte.tapamo@facsciences-uy1.cm	f	t	2025-05-14 15:32:22.778956+00
6	pbkdf2_sha256$600000$eSsNfmmUKuAkdVPSbXcbkC$OBRfq/tq5XgXJF1RyS+C8U0IqIIheRaA61vMJasV3OQ=	2025-05-14 14:16:14.194537+00	f	Franck Feuwo	Franck	TAMWO FEUWO	franck.tamwo@facsciences-uy1.cm	f	t	2025-05-14 10:40:00.851678+00
3	pbkdf2_sha256$600000$xKYstlkTduQn5KOgmGEJND$F9p92Gmcyy8+m3aaF1GbbQkDBy/BAHgncQLUqFQOUgU=	2025-09-02 16:44:38.36804+00	f	lontsi	Ronaldino 	LONTSI LAMBOU	ronaldino.lontsi@facsciences-uy1.cm	f	t	2025-04-23 06:10:59.946241+00
8	pbkdf2_sha256$600000$jnUPoyh3OL6Y9uqtuODK0c$vpu9wbUh/wZeg/joDNRjyBfyIKBAC92kYYGqKsxms8M=	\N	f	La machine Babatack 	Landry	BALEKAMEN BABATACK	balekamenbabatacklandry@gmail.com	f	t	2025-05-14 10:46:14.291974+00
12	pbkdf2_sha256$600000$Ym9wAeI2FWL8oKlfcadiv7$YL+hav/PcV5112MBA1jxM2Seyi2NeMafbTXIMipjIYY=	\N	f	Pegasus NATHANAEL	Nathanael	FETUE FOKO	nathanaelfetue1237@gmail.com	f	t	2025-05-14 15:16:48.286773+00
1	pbkdf2_sha256$600000$o4IKI4Y0RQ9H5UDgxMWMgs$N4sBYKDgB/nneoB9uhzYE2e22bLZjsKvCv0w6bSq13c=	2025-09-05 15:59:49.953284+00	t	admin	Alain	TCHANA	alain.tchana@grenoble-inp.fr	t	t	2025-04-18 03:25:09.901641+00
7	pbkdf2_sha256$600000$JCesYHwiYM2aQqVPyya1YS$ceT8rNQ7RcUIrdgLTl38D1B2w9aW4XmwfQG7+NgeGPk=	\N	f	Romero	Romeo	TCHIAZE FOUOSSO	romerotchiazefouosso@gmail.com	f	t	2025-05-14 10:45:22.54667+00
2	pbkdf2_sha256$600000$TqtSioxM4zSexTKWNppiSJ$W+szFaDrF5XKllTQGoC2nYWgtz+qcNuMJOhtwrNrLcU=	\N	f	Bessala	Parfait	BESSALA BESSALA	bessala2@yahoo.fr	f	t	2025-04-23 06:01:56.885405+00
9	pbkdf2_sha256$600000$di99o2eWjWaP4InleZvq6h$HSf7np/gLIET6/wu3jXLp1seOkQKf24zx9qM0eAORr0=	2025-05-14 14:45:27.498205+00	f	samsam237	samuel	BISSOG	sbissog@gmail.com	f	t	2025-05-14 14:40:31.583332+00
10	pbkdf2_sha256$600000$waw2E0pLEjuHXAaUHA6tVg$SqrYhCBSAEPZmwBA2qIIToPfhIVKmxMkn+yN2Vabv+E=	2025-06-09 14:46:42.472915+00	f	Fideline	Fideline	KUETCHE NGOUFACK	fideline.kuetche@facsciences-uy1.cm	f	t	2025-05-14 14:41:32.093967+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-04-21 10:31:09.980863+00	1	gestion des cookie	1	[{"added": {}}]	12	1
2	2025-04-22 20:29:58.010088+00	2	Assistant de code	1	[{"added": {}}]	12	1
3	2025-04-22 21:07:36.524299+00	3	pageAttention	1	[{"added": {}}]	12	1
4	2025-04-23 02:10:20.916167+00	4	Firecracker	1	[{"added": {}}]	12	1
5	2025-04-23 12:22:06.691414+00	1	Systene d'exploitation	1	[{"added": {}}]	7	1
6	2025-04-23 12:22:45.598696+00	2	ntelligence Artificielle"	1	[{"added": {}}]	7	1
7	2025-05-15 07:04:03.449844+00	2	PageAttention	3		13	1
8	2025-05-15 07:04:18.52005+00	1	PageAttention	3		13	1
9	2025-05-15 07:04:56.882931+00	2	assistant co IA	3		15	1
10	2025-05-15 07:04:56.886168+00	1	PageAttention	3		15	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	labo	categorie
8	labo	contact
9	labo	evenement
10	labo	membre
11	labo	temoignage
12	labo	theme
13	labo	presentation
14	labo	imagepresentation
15	labo	article
16	labo	collaborateur
17	labo	devenir
18	labo	invitation
19	labo	projet
20	labo	historiquetheme
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-04-14 21:09:35.138578+00
2	auth	0001_initial	2025-04-14 21:09:35.205569+00
3	admin	0001_initial	2025-04-14 21:09:35.22301+00
4	admin	0002_logentry_remove_auto_add	2025-04-14 21:09:35.230095+00
5	admin	0003_logentry_add_action_flag_choices	2025-04-14 21:09:35.236405+00
6	contenttypes	0002_remove_content_type_name	2025-04-14 21:09:35.249798+00
7	auth	0002_alter_permission_name_max_length	2025-04-14 21:09:35.257939+00
8	auth	0003_alter_user_email_max_length	2025-04-14 21:09:35.264003+00
9	auth	0004_alter_user_username_opts	2025-04-14 21:09:35.277009+00
10	auth	0005_alter_user_last_login_null	2025-04-14 21:09:35.286657+00
11	auth	0006_require_contenttypes_0002	2025-04-14 21:09:35.289518+00
12	auth	0007_alter_validators_add_error_messages	2025-04-14 21:09:35.297087+00
13	auth	0008_alter_user_username_max_length	2025-04-14 21:09:35.3096+00
14	auth	0009_alter_user_last_name_max_length	2025-04-14 21:09:35.316923+00
15	auth	0010_alter_group_name_max_length	2025-04-14 21:09:35.324946+00
16	auth	0011_update_proxy_permissions	2025-04-14 21:09:35.329634+00
17	auth	0012_alter_user_first_name_max_length	2025-04-14 21:09:35.338131+00
18	labo	0001_initial	2025-04-14 21:09:35.436868+00
19	sessions	0001_initial	2025-04-14 21:09:35.447977+00
20	labo	0002_collaborateur_devenir_invitation_delete_contact_and_more	2025-04-19 05:29:46.376217+00
21	labo	0003_membre_statut_ancien	2025-06-05 02:46:19.648651+00
22	labo	0004_article_commentaire_validation_and_more	2025-06-05 02:46:19.752313+00
23	labo	0005_projet	2025-06-05 02:46:19.828855+00
24	labo	0006_historiquetheme_and_more	2025-06-05 02:46:19.876598+00
25	labo	0007_alter_projet_options_remove_projet_date_fin_prevue_and_more	2025-06-06 12:21:01.767732+00
26	labo	0002_auto_20250607_1449	2025-06-07 15:16:11.020585+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
klzx8lmfci9vp6xth31laahmiqjczmc3	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1u5cMK:vKesC3hKZOp3WlJf9G-85pB-104EnbmAdVeN30Htwe8	2025-05-02 03:25:44.173617+00
37y2ka8rpn19shh1zbtk1xoc3w1nsho7	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1u6fo6:rF1Ffcfik6YsNT6JJjuQYR0QYLsGj209_HigE0-MYuI	2025-05-05 01:18:46.463226+00
he8m0a8mlrio91gyfvx7qiie8qtrpgw8	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1u6n0U:cdf5YDuoJ0PASvFwS1FoPjBkI4aodViRn44w23L55hM	2025-05-05 09:00:02.797795+00
r8vxv379nrguv1shagvp01o3e3yuciqp	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1u6n96:SIJyEm2gNy-DH8hHOBVAPaTfW0AGRjuQ4R6nSSngEYs	2025-05-05 09:08:56.660537+00
24talbbr71vbjbu0pgrwii43z7eovse9	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1u75gV:aHKVX-xeM8XB88Ait-j9-iG6l1GJl8LU0zylSxUbs0Y	2025-05-06 04:56:39.986853+00
69klp48spbtwpqpc118xc7m6k67pz4md	.eJxVjMsOwiAQRf-FtSEFOjxcuvcbyMAMUjU0Ke3K-O_apAvd3nPOfYmI21rj1nmJE4mzGMXpd0uYH9x2QHdst1nmua3LlOSuyIN2eZ2Jn5fD_Tuo2Ou39rZgQaWCzgRWG-IB0IyewOdgEgzgjS1smF0KDhWC0ujAWbIenUri_QHjbjeu:1u7az3:06DzvZqY9MA1lxsIhfa35LDEmj5AGLzC9NZt5o_t_R4	2025-05-07 14:21:53.623806+00
dbf043prp1299ypjvmly3lx8q3fx4zyp	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1u7beI:VWfOq-zp4kjiEqt-jh91airqDVTY39adHJyBn8NDW9Y	2025-05-07 15:04:30.483057+00
xxfga7yu7mo5zji4zuyy8ngrd0okdwnl	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1u7bfb:f3Z9oxf4UVrFHad2xQMAzA6rqoNw8gG_PJENYf5Nh6k	2025-05-07 15:05:51.493653+00
3skq1joe94npd8howoy2f2eltnsf35x4	.eJxVjMsOwiAQRf-FtSEFOjxcuvcbyMAMUjU0Ke3K-O_apAvd3nPOfYmI21rj1nmJE4mzGMXpd0uYH9x2QHdst1nmua3LlOSuyIN2eZ2Jn5fD_Tuo2Ou39rZgQaWCzgRWG-IB0IyewOdgEgzgjS1smF0KDhWC0ujAWbIenUri_QHjbjeu:1u7big:atrRo4vswNoMQ5b9qh8zN8Y1IhpKgRQojej_u-Y22Yg	2025-05-07 15:09:02.741709+00
en7tttjlyla6beq2mr98a8qe0cekryzk	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1u7x6J:fWrl4GWIT9Hp0F78uiIdnyt65U50Zd6QJeMR5u62WaA	2025-05-08 13:58:51.669433+00
c0qsz106apz5rzt3ab87z0lpab6uwrou	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1u7xkh:_J-85FuuIAaMGkAxFY9hkIHHIBirUVTPiwMvaAXMpU4	2025-05-08 14:40:35.666764+00
a87jrs0gyi09kqwkpvacm966yt1q1dhh	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uF8q0:3wycQPD9sWAXVe7RI9mYMqbd6xMkRRqt_76XqrTPru4	2025-05-28 09:55:44.811387+00
dfii0zort8qo4tbiebkbvno0y32twyqn	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uF9F1:w50Riv11VXBB_bR3KXFi4anA1qNJMJeF8VmodrZRSm4	2025-05-28 10:21:35.702057+00
yf6mzbp6ixy5kcu4sbuteuqwqdximvk9	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uF9FH:Xn-p9R0k2NyzGNDWiSlKpx91BpcutaPnIaI8YB1x-fY	2025-05-28 10:21:51.658046+00
jtrce9qvupguphu4ofomjh6nt420e1ox	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uF9Ps:FluUWAfebshWcmsQixoZJcI3YvQETZidYyGTvpiw0jA	2025-05-28 10:32:48.731161+00
hvhue9hjiukav1kyvfab1wxakncwygax	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uF9VM:wIvekkpyiSHWXL0vA6eQUDVj5fQPc_zgAMWkMFBir8w	2025-05-28 10:38:28.129362+00
r8ja7k4hua7wxmfwb12fw1e8b8bwotbh	.eJxVjEEOwiAURO_C2hCgQD8u3fcM5MMHqRqalHZlvLs06UJ3kzdv5s087lvxe0urn4ldmWWXXxYwPlM9CnpgvS88LnVb58APhZ9t49NC6XU73b-Dgq30tSZjwmCdjJqCEnakJHLuWepBSCBM2oxZCamCAzRgXHYCKIKA3Flgny_c5Tek:1uFCu6:1QZmE1TJ9avbUrMx1or1xCQRLKOBV68yU9oMgtplPhk	2025-05-28 14:16:14.1972+00
zd97f5lt89djloszci4qdpodmqgkdbd0	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFDEl:thREoc4m1gI9e-w6pzb4Ectw8UPXpsgkh4XawwXZOsM	2025-05-28 14:37:35.232018+00
7l8qo3i91yzu00wk55rueht9wxt80vgq	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFDGb:sr3yqx-6M1BzZBrEN27P3KN1zjnqNC5kLSd9B-dYPww	2025-05-28 14:39:29.841476+00
go5dsmpv3bl3h73pd4v36rqrs2nk8ubc	.eJxVjDsOwjAQBe_iGlnxZx2bkp4zWLveDQmgWIqTCnF3iJQC2jcz76UybuuYtyZLnlidVVKn342wPGTeAd9xvlVd6rwuE-ld0Qdt-lpZnpfD_TsYsY3fWiBYACs2Op_ISaAhDi5B7NAGZvaY0EYoBL0RHhIn8j7YvhjjDfWden8A2sc3hw:1uFDMN:fL2mL1ulCExiAwpEaWZzj3Orr1K4zs7QadKTxAT1LjQ	2025-05-28 14:45:27.49991+00
l4ksl3fy2v8gkdctkov5ra2moxej02jj	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFDXQ:tn04GzLTFQsJRK0tv7HYnZsCLngUf5eeGlHRbJuVKwI	2025-05-28 14:56:52.815726+00
onpbohg2dk12tqc69jw3ojp76lxocecn	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFEHU:60EDr90oA2gcLD0AkOycGrvx5NjdWeG8Ft4ijvj9_R4	2025-05-28 15:44:28.932738+00
9jvsqec6feh719jk5njf5vy3qelcnfiy	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFEiS:Yuo1A6ONLFb-syI593vqe-L0HN7OsVWe8i6sttzuw0U	2025-05-28 16:12:20.961504+00
yynu8y86hxbyei8rjsktpf2jvg5h89mx	eyJfcGFzc3dvcmRfcmVzZXRfdG9rZW4iOiJjcHN0MmYtNzg3NDAyOTkwNjJkNWYzNGQ1ZDliYmZmMmY2ODVjMDUifQ:1uFEx3:ozzcgkXUdsVDN6myyST7LyRdI_T7bhdP00ggSksFEb4	2025-05-28 16:27:25.188167+00
najm8rto96wl4hq14wztcmdh302aq315	eyJfcGFzc3dvcmRfcmVzZXRfdG9rZW4iOiJjcHN0MmYtNzg3NDAyOTkwNjJkNWYzNGQ1ZDliYmZmMmY2ODVjMDUifQ:1uFF0z:pZIQL8I4x3ekZFNIohUXH0ji1ytpkke2imP4H4jUdvE	2025-05-28 16:31:29.269841+00
q25tvp5ipzvjdgt4uuqsb3q9r4p9ozgq	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFFSs:sU42jkWBapuRDUxT4FeIdYWBeoor2iX-hGdJdFXwgZk	2025-05-28 17:00:18.854628+00
zqo6mve429q71n3im1ynxr9v9o1rhdwx	.eJxVjMsOwiAQRf-FtSG8EZfu_QYyw4BUDSSlXRn_3TbpQrf3nHPfLMK61LiOPMeJ2IVJw06_I0J65rYTekC7d556W-YJ-a7wgw5-65Rf18P9O6gw6laL4lEqrbbCZCc9eofaAtoUEHMpWSp5tlZ7Co4UKEGihGAViCQdGGSfLxVAOE0:1uFFTD:ETG0pU_9eLnMD3LISDxM0IW4Vl6YiVfuRtzopxVox_M	2025-05-28 17:00:39.142919+00
hluai0xdp3qxhklzku26w9u761moxlb8	.eJxVjDsOwyAQBe9CHSE-azAp0_sMaBfWwUmEJWNXUe4eIblI2jcz7y0iHnuJR-MtLllchdbi8jsSpifXTvID632Vaa37tpDsijxpk9Oa-XU73b-Dgq30OhnQQAGNz4PjwZKloBUCIujZjGSsdTh7TyE78By0cyoBI7CyIYzi8wX_szeh:1uFHr0:a_xBl_rNopPBTdSrMn7IRY5Eo4_XuVbLasv2x9R2NzQ	2025-05-28 19:33:22.826435+00
qsjgq6osbqy6y7voxin87j0vlekcj2y0	.eJxVjEEOwiAQRe_C2hBKaQGX7nsGMsMMUjWQlHZlvLtt0oVu_3vvv0WAbc1ha7yEmcRVdE5cfkeE-ORyEHpAuVcZa1mXGeWhyJM2OVXi1-10_w4ytLzXiMnbRAN6R0YzEgGR91p5248DuZhUp63pHSijRr9zy71mhQasswzi8wUusjiq:1uFI9w:LJE4U1kZ1jev6JOWWu_EPFksyobgKgmvCkpcuraKYeM	2025-05-28 19:52:56.251935+00
uplceeq7ruj3huq32rp14zxgq2fkct6j	.eJxVjEEOwiAQRe_C2hBKaQGX7nsGMsMMUjWQlHZlvLtt0oVu_3vvv0WAbc1ha7yEmcRVdE5cfkeE-ORyEHpAuVcZa1mXGeWhyJM2OVXi1-10_w4ytLzXiMnbRAN6R0YzEgGR91p5248DuZhUp63pHSijRr9zy71mhQasswzi8wUusjiq:1uFICg:PmyZCY4KxxPYY9jkvwGmYdQcUE14KFw6dYNcWqZEoy8	2025-05-28 19:55:46.734021+00
lxo1wgy6jrfvbelddl912ae2t1y7vyf6	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFSNN:hoLsnWpVAxcnJaNcXt_kF8m1xuaop7ed5Y51xcYlhd4	2025-05-29 06:47:29.131482+00
ocelf3neipa41xopi17zo4mh0gogyyeo	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFZyd:7JT0uJuscfE0ICfNJqsQPk9EyWxGlpn1sdbcfHGDDbE	2025-05-29 14:54:27.621123+00
aa1zsq6nnntzztojvihvqja4mfl5uqpx	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFp1T:bRe3_xDlf1EH2UFqE1CN5IF9ohuBRS44eLk-YOw0ASc	2025-05-30 06:58:23.837295+00
2wcypy5qhe67wyul7ver0vespj4eyuty	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uFvgy:J_CdDMocsU9nGB1hrO8DsWBNgZiq0ACZBrQkKBMRQmA	2025-05-30 14:05:40.696662+00
247te0wwob7elxdgfbpzil2x2yn3ga2i	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uN0gU:i2ia2reIQby78WqZSI9czmKYQxpT5SaTxVvCUq8nxIE	2025-06-19 02:50:26.912945+00
xp6mg0xlj9vk642ocmazr1qsrptkaxhi	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uNI6B:y-9KDbr7kcc0l6WRA3bTRSZJmTBgW3wqWn3iYrdqFyM	2025-06-19 21:26:07.026631+00
fkya8w0usmmtiohesp8x9uy2oxxn5rqx	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uNSBe:nzlqdc33of66YzVPBzMUTJH4PPX20shmBE7LrcXTbxw	2025-06-20 08:12:26.624769+00
1web0j0oqf1q6y71ljz1sdz5yr4e7d0g	.eJxVjEEOwiAQRe_C2hBKaQGX7nsGMsMMUjWQlHZlvLtt0oVu_3vvv0WAbc1ha7yEmcRVdE5cfkeE-ORyEHpAuVcZa1mXGeWhyJM2OVXi1-10_w4ytLzXiMnbRAN6R0YzEgGR91p5248DuZhUp63pHSijRr9zy71mhQasswzi8wUusjiq:1uNSiS:oLRaE_wJ1AbXQcZVFGJOmj2Wz_0G3U7aWeVHesPuRo8	2025-06-20 08:46:20.093543+00
83282l5t6sumq00eszoaar3r7qnce8em	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uNvY7:fINNbtypaot_2UC9PLnUO28Nfl391zWULlE8Bl1vjno	2025-06-21 15:33:35.710413+00
xe8p30r0ic7ozwx29ztkxogxnuc10iz7	.eJxVjMsOwiAQRf-FtSHlDS7d-w0EmBmpGkhKuzL-uzbpQrf3nHNfLKZtrXEbuMQZ2JmJiZ1-x5zKA9tO4J7arfPS27rMme8KP-jg1w74vBzu30FNo35rTSCEdkJBUBrISp-9taI4naRRCBgslOD9FCCpbJFIogymuELkSRj2_gD8KThV:1uOdlq:Xr2FNqkM94wH7MeHo8qzxq0xQIWqzeR7BbDUGyR5_78	2025-06-23 14:46:42.479864+00
v4vy0gqtrepi3ya5np894c8kxc1rnq36	.eJxVjMsOwiAQRf-FtSG8EZfu_QYyw4BUDSSlXRn_3TbpQrf3nHPfLMK61LiOPMeJ2IVJw06_I0J65rYTekC7d556W-YJ-a7wgw5-65Rf18P9O6gw6laL4lEqrbbCZCc9eofaAtoUEHMpWSp5tlZ7Co4UKEGihGAViCQdGGSfLxVAOE0:1uSevm:Y7n_grEL7OapPvBTlmpHo-O0pAn0lmHl8DKGtAyCtSU	2025-07-04 16:49:34.332649+00
zft5c4qvzryd3f005w5bhi8kzj398zml	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uk0fN:F4mShlBzJS1vECn3-cG1RnL19NZ7CyN1I4ULmXluHs4	2025-08-21 13:28:21.379521+00
p4ht6v44ah51oiwsot9t4uehxnqq3tcr	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uoezo:Rx6obvO4cNxJUmOhsIcde5GvR4LbNrTtzm-iZgga29Y	2025-09-03 09:20:40.62217+00
vj7fptxjz38rhod567rwolr5vil6g0i1	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uofC7:Kmkiteyu9q_apVZgsfzRtyeTVfENL1EygCYH3FsrqiQ	2025-09-03 09:33:23.995735+00
xrpjdelbogro6zqcb8dmftflhz1v3jke	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uofGL:RwGfKgcg35E60cAX1URqPU1cop6pxohfTIFnjviHtmY	2025-09-03 09:37:45.624101+00
c3f0uza68j7i23av4b4vimt3r6xf6upe	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uofPL:WKeRpHpXmfQoFDeE_9HATlSgndZ3wKTdH2P_p_SNqG8	2025-09-03 09:47:03.796664+00
iyxizvszkuj1dcs5rt7r3i8f5gwat7xg	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1ut4Gk:WfMNFn9bVoAnc0tBKYHgWRUTY8BJzvPcmXynDEMiJio	2025-09-15 13:08:22.97209+00
i9xgey78652rjjytuxi1ws6n055fjjsn	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1ut6iN:QawpnhTHam82j6iGIuhc2grcHx-D_23TXBEyf7B4SV8	2025-09-15 15:45:03.677843+00
zi4z1vrpj9sq8st0lhcg4bhwqezatiux	.eJxVjDsOwjAQBe_iGlm2179Q0nMGy95d4wBKpDipEHeHSCmgfTPzXiLlbW1p67ykkcRZgDj9biXjg6cd0D1Pt1niPK3LWOSuyIN2eZ2Jn5fD_TtoubdvHQOghsEb5WytMBgbyOWqXfSDU4wKKGKw6BkDGcPM0fsAVDUUZbIX7w-_rTdU:1utU7a:bqq1cJIjzEPa_eWhhRHttg3vUakXqXH9ufhIh-hgTKc	2025-09-16 16:44:38.371268+00
t6ect1x6resnhso08chikrcm71yoa4ws	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1utU9E:zZCLyCehAktw1tytERnZDFODTGJu3MFNzx7o6_OkmgQ	2025-09-16 16:46:20.99447+00
ha47i7tncugbqu260t856dv02ql1qosg	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1utdBJ:Z5ZtxCh5TXV3tdI0snOi00m9y8Z79Xyg6Tnjw4i8-7o	2025-09-17 02:25:05.748149+00
dwke8qn4a6f1ikhih7fcdk5h9or9nacj	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1utdCL:HbPWmeyvY5UeJ46UzmuxF8nl7VRDsTHekNScNFfsTJQ	2025-09-17 02:26:09.981312+00
9pc2n11kr00sj8g0yvbhju5z32okb008	e30:1utdFI:cMAv9iV1s9LK5tsvurChzHk4lCvO68KKi3JHTc-5kow	2025-09-17 02:29:12.177455+00
jzaineosy65gulpvrfytwbxi6j24f2zl	.eJxVjEEOwiAQRe_C2hAGBItL956BDDODVA1NSrsy3l2bdKHb_977L5VwXWpau8xpZHVWoA6_W0Z6SNsA37HdJk1TW-Yx603RO-36OrE8L7v7d1Cx129tRIJkLMHyYGP0NhtAH5hOJXhxBsgA2yEjO0MEGCGKQ5OBkY7Fi3p_APbQOKA:1uuYqr:fzlIzAoX9ATvB9rWfR0RW9gYgG-yItcZB-lWQZhncyI	2025-09-19 15:59:49.966108+00
\.


--
-- Data for Name: labo_article; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_article (id, titre, contenu, image_principale, date_creation, date_modification, est_publie, auteur_id, commentaire_validation, date_validation, statut_validation, validateur_id) FROM stdin;
6	Test the Security	Cet article est personnel	articles/images/IRTNANOELEC_LOGO_WEB.png	2025-08-20 09:41:20.125662+00	2025-08-20 09:41:20.125705+00	f	1	\N	\N	en_attente	\N
\.


--
-- Data for Name: labo_article_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_article_categories (id, article_id, categorie_id) FROM stdin;
6	6	5
\.


--
-- Data for Name: labo_categorie; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_categorie (id, nom, description) FROM stdin;
5	Cybersecurity	Fake data
\.


--
-- Data for Name: labo_collaborateur; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_collaborateur (id, nom, prenom, titre, institution, description, photo, email, lien) FROM stdin;
1	HAGIMONT	Daniel	Professor	Toulouse INP	France	collaborateurs/photos/Capture_décran_du_2025-04-23_02-58-02.png		
4	VUILLERME	Nicolas	Professor	University of Grenoble Alpes	France	collaborateurs/photos/Capture_décran_du_2025-05-14_11-47-36.png		
3	BROMBERG	David	Professor	University of Rennes	France	collaborateurs/photos/dav.jpeg		
\.


--
-- Data for Name: labo_devenir; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_devenir (id, entreprise, poste, description, realisations, date_debut, lieu, lien, domaine, type_structure, membre_id) FROM stdin;
\.


--
-- Data for Name: labo_evenement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_evenement (id, titre, description, type_evenement, date_debut, date_fin, lieu, image) FROM stdin;
2	Hackathon: L'Aurore de recherche en informatique au cameroun	The primary objective of this hackathon is to expose students to current technological challenges in computer science, particularly in areas such as artificial intelligence and cloud resource management. To make these themes more tangible, problem statements were drawn from the local context—for instance, using AI for malaria detection. In parallel, more fundamental topics, such as integrating AI into operating systems, were included to broaden participants’ perspectives.\r\n\r\nThis hackathon aims to develop several key competencies among students: the ability to quickly solve complex problems, effective collaboration within teams of unfamiliar peers, and the skills to showcase and present their work convincingly. Beyond these immediate outcomes, the event also serves to strengthen cooperation between the participating Cameroonian and French universities.	hackathon	2024-12-22 00:00:00+00	2024-12-28 00:00:00+00	Université de Yaoundé 1 , bibliothèque du département informatique	evenements/images/Capture_décran_du_2025-04-23_10-59-42.png
\.


--
-- Data for Name: labo_historiquetheme; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_historiquetheme (id, date_debut, date_fin, description, date_creation, membre_id, theme_id) FROM stdin;
1	2024-02-14	\N	Thème initial : gestion des cookie	2025-06-05 02:46:21.51673+00	9	1
2	2024-02-08	\N	Thème initial : gestion des cookie	2025-06-05 02:46:21.536597+00	5	1
3	2024-12-01	\N	Thème initial : Assistant de code	2025-06-05 02:46:21.54359+00	6	2
5	2024-12-22	\N	Thème initial : Linux kernel programming	2025-06-06 10:22:55.281587+00	7	2
6	2024-12-01	\N	Thème initial : Linux kernel programming	2025-06-06 10:22:55.295444+00	11	2
7	2024-11-10	\N	Thème initial : Linux kernel programming	2025-06-06 10:22:55.300527+00	3	2
8	2024-11-01	\N	Thème initial : Data Privacy	2025-06-06 10:22:55.304175+00	17	1
\.


--
-- Data for Name: labo_imagepresentation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_imagepresentation (id, image, legende, presentation_id) FROM stdin;
3	presentations/images/synchronous.png	\N	5
4	presentations/images/preempt.png	\N	5
5	presentations/images/context_switch.png	\N	5
\.


--
-- Data for Name: labo_invitation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_invitation (id, email, token, created_at, expires_at, is_used, inviter_id) FROM stdin;
1	lontsilambou@gmail.com	173e31db00154a4286ada03d2bd2f2e8	2025-04-20 18:09:15.808533+00	2025-05-20 18:09:15.808325+00	f	1
2	lontsironaldino@gmail.com	93171cf34a64467e9a625cc1f6352ddf	2025-04-21 01:19:15.791852+00	2025-05-21 01:19:15.791642+00	f	1
3	valeretamwo@gmail.com	8fae20201f5f44cbbbeeac9541db7e2b	2025-04-23 15:10:46.433781+00	2025-05-23 15:10:46.433617+00	t	1
6	lontsilambou@gmail.com	8c8fe32a762b41acaf0920d17c1b8704	2025-09-02 16:13:43.332029+00	2025-09-09 16:13:43.331005+00	t	1
\.


--
-- Data for Name: labo_membre; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_membre (id, photo, titre, bio, linkedin, github, theme_id, user_id, date_arrivee, date_depart, est_ancien, est_responsable, portfolio, statut_ancien, profil_valide, date_validation_profil, validateur_profil_id) FROM stdin;
3	membres/photos/WhatsApp_Image_2025-04-22_at_21.58.35.jpeg	Student		https://www.linkedin.com/in/lambou-ronaldino-lontsi-954895298?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app	https://github.com/LLontsi/	\N	3	2024-11-10	2025-08-23	f	f	https://lontsi.propentatech.com	\N	t	2025-09-02 18:19:50.817999	1
9	membres/photos/Capture_décran_du_2025-05-14_15-37-06.png	Student				1	10	2024-02-14	\N	f	f		\N	t	2025-09-02 18:20:04.415105	1
8	membres/photos/photo_2025-05-06_17-19-14.jpg	Student			https://github.com/samsam237	\N	9	2025-04-01	\N	f	f		\N	f	\N	\N
5	membres/photos/Profile_Image.png	Student		https://www.linkedin.com/in/valere-tamwo-748896229/	http://github.com/valereTamwo/	1	6	2024-02-08	\N	f	f	https://feuwofranck.tech	\N	t	2025-09-02 18:20:11.051175	1
10	membres/photos/zaz.jpg	Student	I am Achaire ZOGO, a seasoned Software Engineer and Networking Specialist with over five years of experience in the industry. My career has been built on a strong technical foundation, complemented by hands-on experience in developing and implementing high-performance software solutions. I have a proven track record of delivering complex projects, leveraging my expertise in both software engineering and networking to create seamless, integrated systems.\r\nMy skill set spans a broad range of disciplines within software development and network engineering. I am proficient in multiple programming languages, including Python, Java, and JavaScript, and have extensive experience with frameworks such as Laravel and Flutter. My deep understanding of networking protocols and infrastructure allows me to design software that is not only functional but also optimized for network efficiency and security. I specialize in bridging the gap between software development and network configuration, ensuring that the applications I create are robust, scalable, and secure.\r\nI envision a future where technology seamlessly integrates into every aspect of our lives, driving innovation and addressing global challenges. My goal is to be at the forefront of this transformation, leveraging my expertise to create technologies that not only meet today’s needs but also anticipate the challenges of tomorrow. Through continuous learning, collaboration, and a relentless pursuit of excellence, I am committed to shaping a future where technology empowers individuals and communities worldwide.	https://www.linkedin.com/in/achaire-zogo	https://github.com/Achaire-Zogo	\N	11	2022-06-14	\N	f	f		\N	t	2025-09-02 18:20:17.926018	1
2	membres/photos/Capture_décran_du_2025-04-23_03-24-57.png	Information System & Software Engineering PhD				\N	2	2015-01-01	\N	f	t		\N	t	2025-09-02 16:55:59.309849	1
7	membres/photos/IMG-20250327-WA0000.jpg	Student 		https://www.linkedin.com/in/landry-balekamen-babatack-62857a2b4?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app		2	8	2024-12-22	\N	f	f		\N	t	2025-09-02 18:19:18.212767	1
11	membres/photos/IMG_20240922_111108_150.jpg	Student		https://www.linkedin.com/in/nathanael-fetue-foko		2	12	2024-12-01	\N	f	f		\N	t	2025-09-02 18:19:31.152438	1
6	membres/photos/IMG_0944.HEIC	Student		https://www.linkedin.com/in/romero-tchiaze-fouosso-2029aa32b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app		2	7	2024-12-01	\N	f	f		\N	t	2025-09-02 18:19:42.620077	1
17	membres/photos/POTRAIT.jpg	Student	I am a Level 4 student at Polytechnique Yaoundé, passionate about Cybersecurity, System Programming, and AI. I have strong interests in Astronomy, Philosophy, and History, especially the link between identity and culture. Outside academics, I enjoy music, football, and self-reflection through writing.		https://github.com/lado-saha/	1	18	2024-11-01	\N	f	f		\N	t	2025-09-02 18:19:58.637701	1
1	membres/photos/alain.png	Professor	Alain Tchana is from Nkongsamba (https://en.wikipedia.org/wiki/Nkongsamba), a city in Cameroon. He is gratuated from University of Yaoundé I in 2008. Then he received his PhD in computer science in 2011 at Toulouse INP. Since September 2022 he is Professor at Grenoble INP in France. Before Grenoble, Alain Tchana was Assistant Professor at Toulouse INP (2013-2018), Professor at Nice University (2018-2019), and Professor at ENS Lyon (2019-2022). His main research interests are Virtualization and Operating Systems. Simply, Alain Tchana is a Systems guy! He has published more than 60 research papers in major Systems, Middleware, Network, and Security conferences including EuroSys, USENIX ATC, INFOCOM, VEE, Middleware, RAID, and DSN. He has also served as PC member in several conferences including USENIX ATC, EuroSys, NSDI, and DSN. Alain Tchana has co-supervised several PhD students, six of whom are pursuing their career in academia. He has received two major prizes: the 2021 CNRS GDR RSD best junior researcher awards in France, and the 2021 Prix de la Francophonie pour Jeunes chercheurs.	https://www.linkedin.com/in/pr-alain-tchana-72516722/	\N	\N	1	2015-01-01	\N	f	t	https://lig-membres.imag.fr/tchanaa/index.html	\N	f	\N	\N
\.


--
-- Data for Name: labo_membre_themes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_membre_themes (id, membre_id, theme_id) FROM stdin;
1	3	2
\.


--
-- Data for Name: labo_presentation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_presentation (id, titre, description, fichier, type_fichier, date_creation, date_modification, membre_id, theme_id, fichier_public) FROM stdin;
5	Cookie Crawler	Personal Data	presentations/fichiers/osdi25-shen-weihang.pdf	pdf	2025-08-20 09:41:04.375252+00	2025-09-02 12:21:59.419206+00	1	1	f
\.


--
-- Data for Name: labo_projet; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_projet (id, titre, description, date_debut, statut, date_creation, est_public, responsable_id, theme_id) FROM stdin;
1	Cookie Crawler	We aim at building an automatic cookie crawler.	2024-04-01	en_cours	2025-06-05 21:52:52.976436+00	t	1	1
\.


--
-- Data for Name: labo_projet_collaborateurs_externes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_projet_collaborateurs_externes (id, projet_id, collaborateur_id) FROM stdin;
1	1	1
2	1	3
3	1	4
\.


--
-- Data for Name: labo_projet_participants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_projet_participants (id, projet_id, membre_id) FROM stdin;
1	1	9
2	1	5
3	1	17
4	1	1
\.


--
-- Data for Name: labo_temoignage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_temoignage (id, nom, role, contenu, photo, date) FROM stdin;
2	Nathanael FETUE	Student	Beta Lab is not just a computer science lab. It’s a place where you discover your true potential. There, I learned to push beyond my limits, to embrace rigor, curiosity, and, above all, perseverance.\r\n\r\nAt the heart of a passionate, dynamic team always willing to share, I found more than just a work environment—I found a scientific family. Beta Lab inspired me, challenged me, and helped me grow both technically and personally.\r\n\r\nI leave with strong skills, meaningful memories, and, most importantly, the conviction that anything is possible when you're surrounded by the right people. Thank you, Beta Lab, for the momentum, the vision, and this incredible journey.	temoignages/photos/photo_2025-04-15_16-54-53.jpg	2024-01-01
\.


--
-- Data for Name: labo_theme; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.labo_theme (id, nom, description) FROM stdin;
4	Firecracker-based IaaS management framework	A IaaS manager for the camerounian context
1	Data Privacy	Building systems which respect data privacy
2	Linux kernel programming	How LLM can assist Linux kernel programmers?
7	Cloud comptuting and FAAS	
8	RGPD and Personnal data management	
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 19, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 10, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 26, true);


--
-- Name: labo_article_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_article_categories_id_seq', 6, true);


--
-- Name: labo_article_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_article_id_seq', 6, true);


--
-- Name: labo_categorie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_categorie_id_seq', 5, true);


--
-- Name: labo_collaborateur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_collaborateur_id_seq', 4, true);


--
-- Name: labo_devenir_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_devenir_id_seq', 1, true);


--
-- Name: labo_evenement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_evenement_id_seq', 3, true);


--
-- Name: labo_historiquetheme_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_historiquetheme_id_seq', 8, true);


--
-- Name: labo_imagepresentation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_imagepresentation_id_seq', 5, true);


--
-- Name: labo_invitation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_invitation_id_seq', 6, true);


--
-- Name: labo_membre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_membre_id_seq', 17, true);


--
-- Name: labo_membre_themes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_membre_themes_id_seq', 1, true);


--
-- Name: labo_presentation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_presentation_id_seq', 5, true);


--
-- Name: labo_projet_collaborateurs_externes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_projet_collaborateurs_externes_id_seq', 3, true);


--
-- Name: labo_projet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_projet_id_seq', 1, true);


--
-- Name: labo_projet_participants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_projet_participants_id_seq', 4, true);


--
-- Name: labo_temoignage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_temoignage_id_seq', 2, true);


--
-- Name: labo_theme_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.labo_theme_id_seq', 8, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: labo_article_categories labo_article_categories_article_id_categorie_id_f10c6eef_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_article_categories
    ADD CONSTRAINT labo_article_categories_article_id_categorie_id_f10c6eef_uniq UNIQUE (article_id, categorie_id);


--
-- Name: labo_article_categories labo_article_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_article_categories
    ADD CONSTRAINT labo_article_categories_pkey PRIMARY KEY (id);


--
-- Name: labo_article labo_article_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_article
    ADD CONSTRAINT labo_article_pkey PRIMARY KEY (id);


--
-- Name: labo_categorie labo_categorie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_categorie
    ADD CONSTRAINT labo_categorie_pkey PRIMARY KEY (id);


--
-- Name: labo_collaborateur labo_collaborateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_collaborateur
    ADD CONSTRAINT labo_collaborateur_pkey PRIMARY KEY (id);


--
-- Name: labo_devenir labo_devenir_membre_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_devenir
    ADD CONSTRAINT labo_devenir_membre_id_key UNIQUE (membre_id);


--
-- Name: labo_devenir labo_devenir_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_devenir
    ADD CONSTRAINT labo_devenir_pkey PRIMARY KEY (id);


--
-- Name: labo_evenement labo_evenement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_evenement
    ADD CONSTRAINT labo_evenement_pkey PRIMARY KEY (id);


--
-- Name: labo_historiquetheme labo_historiquetheme_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_historiquetheme
    ADD CONSTRAINT labo_historiquetheme_pkey PRIMARY KEY (id);


--
-- Name: labo_imagepresentation labo_imagepresentation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_imagepresentation
    ADD CONSTRAINT labo_imagepresentation_pkey PRIMARY KEY (id);


--
-- Name: labo_invitation labo_invitation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_invitation
    ADD CONSTRAINT labo_invitation_pkey PRIMARY KEY (id);


--
-- Name: labo_invitation labo_invitation_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_invitation
    ADD CONSTRAINT labo_invitation_token_key UNIQUE (token);


--
-- Name: labo_membre labo_membre_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_membre
    ADD CONSTRAINT labo_membre_pkey PRIMARY KEY (id);


--
-- Name: labo_membre_themes labo_membre_themes_membre_id_theme_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_membre_themes
    ADD CONSTRAINT labo_membre_themes_membre_id_theme_id_key UNIQUE (membre_id, theme_id);


--
-- Name: labo_membre_themes labo_membre_themes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_membre_themes
    ADD CONSTRAINT labo_membre_themes_pkey PRIMARY KEY (id);


--
-- Name: labo_membre labo_membre_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_membre
    ADD CONSTRAINT labo_membre_user_id_key UNIQUE (user_id);


--
-- Name: labo_presentation labo_presentation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_presentation
    ADD CONSTRAINT labo_presentation_pkey PRIMARY KEY (id);


--
-- Name: labo_projet_collaborateurs_externes labo_projet_collaborateu_projet_id_collaborateur__bd029632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet_collaborateurs_externes
    ADD CONSTRAINT labo_projet_collaborateu_projet_id_collaborateur__bd029632_uniq UNIQUE (projet_id, collaborateur_id);


--
-- Name: labo_projet_collaborateurs_externes labo_projet_collaborateurs_externes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet_collaborateurs_externes
    ADD CONSTRAINT labo_projet_collaborateurs_externes_pkey PRIMARY KEY (id);


--
-- Name: labo_projet_participants labo_projet_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet_participants
    ADD CONSTRAINT labo_projet_participants_pkey PRIMARY KEY (id);


--
-- Name: labo_projet_participants labo_projet_participants_projet_id_membre_id_6ed9ddda_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet_participants
    ADD CONSTRAINT labo_projet_participants_projet_id_membre_id_6ed9ddda_uniq UNIQUE (projet_id, membre_id);


--
-- Name: labo_projet labo_projet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet
    ADD CONSTRAINT labo_projet_pkey PRIMARY KEY (id);


--
-- Name: labo_temoignage labo_temoignage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_temoignage
    ADD CONSTRAINT labo_temoignage_pkey PRIMARY KEY (id);


--
-- Name: labo_theme labo_theme_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_theme
    ADD CONSTRAINT labo_theme_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: labo_article_auteur_id_4c53a3f7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_article_auteur_id_4c53a3f7 ON public.labo_article USING btree (auteur_id);


--
-- Name: labo_article_categories_article_id_30e167c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_article_categories_article_id_30e167c2 ON public.labo_article_categories USING btree (article_id);


--
-- Name: labo_article_categories_categorie_id_c9843ffb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_article_categories_categorie_id_c9843ffb ON public.labo_article_categories USING btree (categorie_id);


--
-- Name: labo_article_validateur_id_393ba0dc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_article_validateur_id_393ba0dc ON public.labo_article USING btree (validateur_id);


--
-- Name: labo_historiquetheme_membre_id_56f91868; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_historiquetheme_membre_id_56f91868 ON public.labo_historiquetheme USING btree (membre_id);


--
-- Name: labo_historiquetheme_theme_id_138a3a8f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_historiquetheme_theme_id_138a3a8f ON public.labo_historiquetheme USING btree (theme_id);


--
-- Name: labo_imagepresentation_presentation_id_0d5d1ab7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_imagepresentation_presentation_id_0d5d1ab7 ON public.labo_imagepresentation USING btree (presentation_id);


--
-- Name: labo_invitation_inviter_id_2fc5017d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_invitation_inviter_id_2fc5017d ON public.labo_invitation USING btree (inviter_id);


--
-- Name: labo_invitation_token_bda8c991_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_invitation_token_bda8c991_like ON public.labo_invitation USING btree (token varchar_pattern_ops);


--
-- Name: labo_membre_theme_id_1c272741; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_membre_theme_id_1c272741 ON public.labo_membre USING btree (theme_id);


--
-- Name: labo_membre_themes_membre_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_membre_themes_membre_id_idx ON public.labo_membre_themes USING btree (membre_id);


--
-- Name: labo_membre_themes_theme_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_membre_themes_theme_id_idx ON public.labo_membre_themes USING btree (theme_id);


--
-- Name: labo_presentation_membre_id_a3dcef5c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_presentation_membre_id_a3dcef5c ON public.labo_presentation USING btree (membre_id);


--
-- Name: labo_presentation_theme_id_ef9bbeed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_presentation_theme_id_ef9bbeed ON public.labo_presentation USING btree (theme_id);


--
-- Name: labo_projet_collaborateurs_externes_collaborateur_id_1a5dde9d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_projet_collaborateurs_externes_collaborateur_id_1a5dde9d ON public.labo_projet_collaborateurs_externes USING btree (collaborateur_id);


--
-- Name: labo_projet_collaborateurs_externes_projet_id_6a830bba; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_projet_collaborateurs_externes_projet_id_6a830bba ON public.labo_projet_collaborateurs_externes USING btree (projet_id);


--
-- Name: labo_projet_participants_membre_id_0dbd8462; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_projet_participants_membre_id_0dbd8462 ON public.labo_projet_participants USING btree (membre_id);


--
-- Name: labo_projet_participants_projet_id_d6e66ee3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_projet_participants_projet_id_d6e66ee3 ON public.labo_projet_participants USING btree (projet_id);


--
-- Name: labo_projet_responsable_id_50c11a98; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_projet_responsable_id_50c11a98 ON public.labo_projet USING btree (responsable_id);


--
-- Name: labo_projet_theme_id_6cd33fda; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labo_projet_theme_id_6cd33fda ON public.labo_projet USING btree (theme_id);


--
-- Name: unique_theme_actuel_par_membre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_theme_actuel_par_membre ON public.labo_historiquetheme USING btree (membre_id, theme_id) WHERE (date_fin IS NULL);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_article labo_article_auteur_id_4c53a3f7_fk_labo_membre_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_article
    ADD CONSTRAINT labo_article_auteur_id_4c53a3f7_fk_labo_membre_id FOREIGN KEY (auteur_id) REFERENCES public.labo_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_article_categories labo_article_categor_categorie_id_c9843ffb_fk_labo_cate; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_article_categories
    ADD CONSTRAINT labo_article_categor_categorie_id_c9843ffb_fk_labo_cate FOREIGN KEY (categorie_id) REFERENCES public.labo_categorie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_article_categories labo_article_categories_article_id_30e167c2_fk_labo_article_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_article_categories
    ADD CONSTRAINT labo_article_categories_article_id_30e167c2_fk_labo_article_id FOREIGN KEY (article_id) REFERENCES public.labo_article(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_article labo_article_validateur_id_393ba0dc_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_article
    ADD CONSTRAINT labo_article_validateur_id_393ba0dc_fk_auth_user_id FOREIGN KEY (validateur_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_devenir labo_devenir_membre_id_2e776b96_fk_labo_membre_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_devenir
    ADD CONSTRAINT labo_devenir_membre_id_2e776b96_fk_labo_membre_id FOREIGN KEY (membre_id) REFERENCES public.labo_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_historiquetheme labo_historiquetheme_membre_id_56f91868_fk_labo_membre_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_historiquetheme
    ADD CONSTRAINT labo_historiquetheme_membre_id_56f91868_fk_labo_membre_id FOREIGN KEY (membre_id) REFERENCES public.labo_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_historiquetheme labo_historiquetheme_theme_id_138a3a8f_fk_labo_theme_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_historiquetheme
    ADD CONSTRAINT labo_historiquetheme_theme_id_138a3a8f_fk_labo_theme_id FOREIGN KEY (theme_id) REFERENCES public.labo_theme(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_imagepresentation labo_imagepresentati_presentation_id_0d5d1ab7_fk_labo_pres; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_imagepresentation
    ADD CONSTRAINT labo_imagepresentati_presentation_id_0d5d1ab7_fk_labo_pres FOREIGN KEY (presentation_id) REFERENCES public.labo_presentation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_invitation labo_invitation_inviter_id_2fc5017d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_invitation
    ADD CONSTRAINT labo_invitation_inviter_id_2fc5017d_fk_auth_user_id FOREIGN KEY (inviter_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_membre labo_membre_theme_id_1c272741_fk_labo_theme_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_membre
    ADD CONSTRAINT labo_membre_theme_id_1c272741_fk_labo_theme_id FOREIGN KEY (theme_id) REFERENCES public.labo_theme(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_membre_themes labo_membre_themes_membre_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_membre_themes
    ADD CONSTRAINT labo_membre_themes_membre_id_fkey FOREIGN KEY (membre_id) REFERENCES public.labo_membre(id) ON DELETE CASCADE;


--
-- Name: labo_membre_themes labo_membre_themes_theme_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_membre_themes
    ADD CONSTRAINT labo_membre_themes_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.labo_theme(id) ON DELETE CASCADE;


--
-- Name: labo_membre labo_membre_user_id_94a05c15_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_membre
    ADD CONSTRAINT labo_membre_user_id_94a05c15_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_presentation labo_presentation_membre_id_a3dcef5c_fk_labo_membre_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_presentation
    ADD CONSTRAINT labo_presentation_membre_id_a3dcef5c_fk_labo_membre_id FOREIGN KEY (membre_id) REFERENCES public.labo_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_presentation labo_presentation_theme_id_ef9bbeed_fk_labo_theme_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_presentation
    ADD CONSTRAINT labo_presentation_theme_id_ef9bbeed_fk_labo_theme_id FOREIGN KEY (theme_id) REFERENCES public.labo_theme(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_projet_collaborateurs_externes labo_projet_collabor_collaborateur_id_1a5dde9d_fk_labo_coll; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet_collaborateurs_externes
    ADD CONSTRAINT labo_projet_collabor_collaborateur_id_1a5dde9d_fk_labo_coll FOREIGN KEY (collaborateur_id) REFERENCES public.labo_collaborateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_projet_collaborateurs_externes labo_projet_collabor_projet_id_6a830bba_fk_labo_proj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet_collaborateurs_externes
    ADD CONSTRAINT labo_projet_collabor_projet_id_6a830bba_fk_labo_proj FOREIGN KEY (projet_id) REFERENCES public.labo_projet(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_projet_participants labo_projet_participants_membre_id_0dbd8462_fk_labo_membre_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet_participants
    ADD CONSTRAINT labo_projet_participants_membre_id_0dbd8462_fk_labo_membre_id FOREIGN KEY (membre_id) REFERENCES public.labo_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_projet_participants labo_projet_participants_projet_id_d6e66ee3_fk_labo_projet_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet_participants
    ADD CONSTRAINT labo_projet_participants_projet_id_d6e66ee3_fk_labo_projet_id FOREIGN KEY (projet_id) REFERENCES public.labo_projet(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_projet labo_projet_responsable_id_50c11a98_fk_labo_membre_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet
    ADD CONSTRAINT labo_projet_responsable_id_50c11a98_fk_labo_membre_id FOREIGN KEY (responsable_id) REFERENCES public.labo_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labo_projet labo_projet_theme_id_6cd33fda_fk_labo_theme_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labo_projet
    ADD CONSTRAINT labo_projet_theme_id_6cd33fda_fk_labo_theme_id FOREIGN KEY (theme_id) REFERENCES public.labo_theme(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

