version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_labo_site
    restart: always
    environment:
      POSTGRES_DB: labo_informatique_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    networks:
      - labo_network
    volumes:
      # Volume nommé pour persister les données
      - postgres_data:/var/lib/postgresql/data
      # Dump uniquement si la DB n'existe pas
      #- ./dump_labo_informatique.sql:/docker-entrypoint-initdb.d/dump_labo_informatique.sql

  site-labo:
    image: lontsi/betalab:latest
    container_name: site-labo
    restart: unless-stopped
    ports:
      - "8022:8000"
    networks:
      - labo_network
    depends_on:
      - postgres
    stdin_open: true
    tty: true

networks:
  labo_network:
    driver: bridge

# Définir le volume nommé
volumes:
  postgres_data:
    driver: local