version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_labo_site
    restart: always
    environment:
      POSTGRES_DB: labo_informatique_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    networks:
      - labo_network
    volumes:
      - ./dump_labo_informatique.sql:/docker-entrypoint-initdb.d/dump_labo_informatique.sql

  site-labo:
    image: lontsi/betalab:latest
    container_name: site-labo
    restart: unless-stopped
    ports:
      - "8022:8000"
    networks:
      - labo_network
    depends_on:
      - postgres
    stdin_open: true      # équivalent à -it
    tty: true
    # command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn labo_informatique.wsgi:application --bind 0.0.0.0:8000"
networks:
  labo_network:
    driver: bridge

