# Generated by Django 4.2.6 on 2025-04-19 05:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collaborateurs/photos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lien', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
            },
        ),
        migrations.CreateModel(
            name='Devenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('realisations', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('lien', models.URLField(blank=True, null=True)),
                ('domaine', models.CharField(max_length=100)),
                ('type_structure', models.CharField(choices=[('academique', 'Académique'), ('industrie', 'Industrie'), ('startup', 'Startup')], default='industrie', max_length=20)),
            ],
            options={
                'verbose_name': 'Devenir',
                'verbose_name_plural': 'Devenirs',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='evenement',
            options={'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterModelOptions(
            name='imagepresentation',
            options={'verbose_name': 'Image de présentation', 'verbose_name_plural': 'Images de présentation'},
        ),
        migrations.AlterModelOptions(
            name='membre',
            options={'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Présentation', 'verbose_name_plural': 'Présentations'},
        ),
        migrations.AlterModelOptions(
            name='temoignage',
            options={'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Thème', 'verbose_name_plural': 'Thèmes'},
        ),
        migrations.AddField(
            model_name='membre',
            name='date_arrivee',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='est_ancien',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='est_responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.membre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='labo.categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='est_publie',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/images/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('conference', 'Conférence'), ('seminaire', 'Séminaire'), ('hackathon', 'Hackathon'), ('atelier', 'Atelier'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='membre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='membres/photos/'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labo.theme'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='fichier',
            field=models.FileField(upload_to='presentations/fichiers/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.membre'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labo.theme'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='type_fichier',
            field=models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('docx', 'Word'), ('other', 'Autre')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='temoignages/photos/'),
        ),
        migrations.AddField(
            model_name='devenir',
            name='membre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='labo.membre'),
        ),
    ]
