# Generated by Django 4.2.6 on 2025-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0002_collaborateur_devenir_invitation_delete_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='statut_ancien',
            field=models.CharField(blank=True, choices=[('parti', 'A quitté le laboratoire'), ('assistant', "Reste comme assistant à l'encadrement")], help_text="Statut de l'ancien membre", max_length=20, null=True),
        ),
    ]
