# Generated by Django 4.2.6 on 2025-05-27 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labo', '0003_membre_statut_ancien'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commentaire_validation',
            field=models.TextField(blank=True, help_text="Commentaire de l'administrateur lors de la validation/rejet", null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', help_text="Statut de validation par l'administrateur", max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='validateur',
            field=models.ForeignKey(blank=True, help_text="Administrateur qui a validé l'article", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
