# Generated by Django 4.2.6 on 2025-05-27 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0004_article_commentaire_validation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_courte', models.CharField(help_text='Description courte pour les listes', max_length=300)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='projets/images/')),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('type_projet', models.CharField(choices=[('recherche', 'Recherche'), ('developpement', 'Développement'), ('formation', 'Formation'), ('collaboration', 'Collaboration'), ('innovation', 'Innovation')], default='recherche', max_length=20)),
                ('lien_solution', models.URLField(blank=True, help_text='Lien vers la solution/démo', null=True)),
                ('lien_github', models.URLField(blank=True, help_text='Lien vers le repository GitHub', null=True)),
                ('lien_documentation', models.URLField(blank=True, help_text='Lien vers la documentation', null=True)),
                ('lien_publication', models.URLField(blank=True, help_text='Lien vers publication scientifique', null=True)),
                ('technologies', models.CharField(blank=True, help_text='Technologies utilisées (séparées par des virgules)', max_length=500)),
                ('mots_cles', models.CharField(blank=True, help_text='Mots-clés (séparés par des virgules)', max_length=300)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_public', models.BooleanField(default=True, help_text='Le projet est-il visible publiquement ?')),
                ('collaborateurs_externes', models.ManyToManyField(blank=True, help_text='Collaborateurs externes au projet', to='labo.collaborateur')),
                ('participants', models.ManyToManyField(blank=True, related_name='projets_participant', to='labo.membre')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_responsable', to='labo.membre')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_debut'],
            },
        ),
    ]
