# Generated by Django 4.2.6 on 2025-05-30 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0005_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text='Date de début de ce thème de recherche')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de ce thème (vide si actuel)', null=True)),
                ('description', models.TextField(blank=True, help_text='Description des travaux réalisés dans ce thème')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_themes', to='labo.membre')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.theme')),
            ],
            options={
                'verbose_name': 'Historique de thème',
                'verbose_name_plural': 'Historiques de thèmes',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddConstraint(
            model_name='historiquetheme',
            constraint=models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('membre', 'theme'), name='unique_theme_actuel_par_membre'),
        ),
    ]
