# Generated by Django 4.2.6 on 2025-06-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0006_historiquetheme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_fin_prevue',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_fin_reelle',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='description_courte',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='image_principale',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='lien_documentation',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='lien_github',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='lien_publication',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='lien_solution',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='mots_cles',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='type_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='theme',
            field=models.ForeignKey(help_text='Thématique de recherche associée', null=True, on_delete=django.db.models.deletion.CASCADE, to='labo.theme'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
