# Generated by Django 4.2.6 on 2025-06-07 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labo', '0007_alter_projet_options_remove_projet_date_fin_prevue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='commentaire_validation',
            field=models.TextField(blank=True, help_text="Commentaire de l'administrateur lors de la validation/rejet", null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='est_publie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', help_text="Statut de validation par l'administrateur", max_length=20),
        ),
        migrations.AddField(
            model_name='presentation',
            name='validateur',
            field=models.ForeignKey(blank=True, help_text='Administrateur qui a validé la présentation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
