# Generated by Django 4.2.6 on 2025-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0008_presentation_commentaire_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='est_publie',
            field=models.BooleanField(default=False),
        ),
    ]
